title: CWRlab SoilData
description: A soil data schema library
theme: just-the-docs

url: https://agrifooddatacanada.github.io/CWRlab/

aux_links:
  Template Repository: https://github.com/agrifooddatacanada/CWRlab
